/**
 *
 * $Id$
 */
package gemRBAC.validation;

import gemRBAC.AbsoluteTE;
import gemRBAC.RelativeTE;
import gemRBAC.TimeUnitType;

import java.math.BigInteger;

/**
 * A sample validator interface for {@link gemRBAC.ActivationDuration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivationDurationValidator {
	boolean validate();

	boolean validateIdDuration(String value);
	boolean validateValue(BigInteger value);
	boolean validateTimeUnit(TimeUnitType value);
	boolean validateIsContinous(boolean value);
	boolean validateAexp(AbsoluteTE value);
	boolean validateRexp(RelativeTE value);
}
