/**
 *
 * $Id$
 */
package gemRBAC.validation;

import gemRBAC.CardinalType;

/**
 * A sample validator interface for {@link gemRBAC.CardinalDirection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CardinalDirectionValidator {
	boolean validate();

	boolean validateDirection(CardinalType value);
	boolean validateAngle(double value);
}
