/**
 *
 * $Id$
 */
package gemRBAC.validation;

import gemRBAC.Delegation;
import gemRBAC.Permission;
import gemRBAC.Role;
import gemRBAC.User;
import gemRBAC.delegationType;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link gemRBAC.Delegation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DelegationValidator {
	boolean validate();

	boolean validateIdDelegation(String value);
	boolean validateIsRevoked(boolean value);
	boolean validateIsTransfer(delegationType value);
	boolean validateIsTotal(boolean value);
	boolean validateStartDate(Date value);
	boolean validateEndDate(Date value);
	boolean validateDelegatorUser(User value);
	boolean validateDelegateUser(User value);
	boolean validateRevokingUser(User value);
	boolean validateDelegatedDelegation(EList<Delegation> value);
	boolean validateDelegatedPermissions(EList<Permission> value);
	boolean validateMaxDepth(int value);
	boolean validateDelegatedRole(Role value);
}
