/**
 *
 * $Id$
 */
package gemRBAC.validation;

import gemRBAC.Operation;
import gemRBAC.Permission;
import gemRBAC.RBACContext;
import gemRBAC.Role;
import gemRBAC.User;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link gemRBAC.History}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HistoryValidator {
	boolean validate();

	boolean validateIdLog(String value);
	boolean validateRole(Role value);
	boolean validateObject(gemRBAC.Object value);
	boolean validateOp(Operation value);
	boolean validatePermission(Permission value);
	boolean validateContext(EList<RBACContext> value);
	boolean validateUser(User value);
}
