/**
 *
 * $Id$
 */
package gemRBAC.validation;

import gemRBAC.TimePoint;
import gemRBAC.TimeUnitType;

/**
 * A sample validator interface for {@link gemRBAC.PeriodicTime}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PeriodicTimeValidator {
	boolean validate();

	boolean validateFrequency(int value);
	boolean validateTimeUnit(TimeUnitType value);
	boolean validateIdPeriodicTime(String value);
	boolean validateNextStart(TimePoint value);
}
