/**
 *
 * $Id$
 */
package gemRBAC.validation;

import gemRBAC.Delegation;
import gemRBAC.History;
import gemRBAC.Operation;
import gemRBAC.RBACContext;
import gemRBAC.Role;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link gemRBAC.Permission}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PermissionValidator {
	boolean validate();

	boolean validateRoles(EList<Role> value);
	boolean validateOperations(EList<Operation> value);
	boolean validateIdPermission(String value);
	boolean validateObject(gemRBAC.Object value);
	boolean validateDelegation(EList<Delegation> value);
	boolean validateLogPermission(EList<History> value);
	boolean validatePermissionContextAssignment(EList<RBACContext> value);
	boolean validatePermissionContextEnabling(EList<RBACContext> value);
}
