/**
 *
 * $Id$
 */
package gemRBAC.validation;

import gemRBAC.Point;

/**
 * A sample validator interface for {@link gemRBAC.Polyline}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PolylineValidator {
	boolean validate();

	boolean validateStart(Point value);
	boolean validateEnd(Point value);
}
