/**
 *
 * $Id$
 */
package gemRBAC.validation;

import gemRBAC.History;
import gemRBAC.Permission;
import gemRBAC.Role;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link gemRBAC.RBACContext}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RBACContextValidator {
	boolean validate();

	boolean validateLogContext(EList<History> value);
	boolean validateP1(Permission value);
	boolean validateP2(Permission value);
	boolean validateR1(Role value);
	boolean validateR2(Role value);
	boolean validateIdContext(String value);
}
