/**
 *
 * $Id$
 */
package gemRBAC.validation;

import gemRBAC.Location;
import gemRBAC.RelativeDirection;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link gemRBAC.RelativeLocation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RelativeLocationValidator {
	boolean validate();

	boolean validateLocation(EList<Location> value);
	boolean validateRelativeLocID(String value);
	boolean validateDistance(double value);
	boolean validateUnit(String value);
	boolean validateRelativedirection(RelativeDirection value);
}
