/**
 *
 * $Id$
 */
package gemRBAC.validation;

import gemRBAC.Delegation;
import gemRBAC.History;
import gemRBAC.Permission;
import gemRBAC.RBACContext;
import gemRBAC.Role;
import gemRBAC.Session;
import gemRBAC.User;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link gemRBAC.Role}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RoleValidator {
	boolean validate();

	boolean validateIdRole(String value);
	boolean validateUsers(EList<User> value);
	boolean validateIsDependent(boolean value);
	boolean validateIsStrong(boolean value);
	boolean validateIsCascading(boolean value);
	boolean validateSessionsA(EList<Session> value);
	boolean validateSessionsE(EList<Session> value);
	boolean validatePermissions(EList<Permission> value);
	boolean validateJuniors(EList<Role> value);
	boolean validateSeniors(EList<Role> value);
	boolean validateUser(EList<User> value);
	boolean validateDelegation(EList<Delegation> value);
	boolean validateRoleContextAssignment(EList<RBACContext> value);
	boolean validateRoleContextEnabling(EList<RBACContext> value);
	boolean validateLogRole(EList<History> value);
}
