/**
 *
 * $Id$
 */
package gemRBAC.validation;

import gemRBAC.ActivationDuration;
import gemRBAC.Delegation;
import gemRBAC.History;
import gemRBAC.Location;
import gemRBAC.Operation;
import gemRBAC.PeriodicTime;
import gemRBAC.Permission;
import gemRBAC.RBACContext;
import gemRBAC.RBACUtility;
import gemRBAC.RelativeDirection;
import gemRBAC.RelativeLocation;
import gemRBAC.Role;
import gemRBAC.Session;
import gemRBAC.User;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link gemRBAC.Root}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RootValidator {
	boolean validate();

	boolean validateSys(RBACUtility value);
	boolean validateObj(EList<gemRBAC.Object> value);
	boolean validateOp(EList<Operation> value);
	boolean validateC(EList<RBACContext> value);
	boolean validateP(EList<Permission> value);
	boolean validateR(EList<Role> value);
	boolean validateS(EList<Session> value);
	boolean validateU(EList<User> value);
	boolean validateD(EList<Delegation> value);
	boolean validateLog(EList<History> value);
	boolean validateDur(EList<ActivationDuration> value);
	boolean validatePeriod(EList<PeriodicTime> value);
	boolean validateRloc(EList<RelativeLocation> value);
	boolean validateRd(EList<RelativeDirection> value);
	boolean validateLoc(EList<Location> value);
}
