/**
 *
 * $Id$
 */
package gemRBAC.validation;

import gemRBAC.Location;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link gemRBAC.SpatialContext}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SpatialContextValidator {
	boolean validate();

	boolean validateLabel(String value);
	boolean validateLocation(EList<Location> value);
}
