/**
 *
 * $Id$
 */
package gemRBAC.validation;

import gemRBAC.AbsoluteTE;
import gemRBAC.RelativeTE;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link gemRBAC.TimeExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TimeExpressionValidator {
	boolean validate();

	boolean validateAbsolute(EList<AbsoluteTE> value);
	boolean validateRelative(EList<RelativeTE> value);
	boolean validateIdTimeExpr(String value);
}
