/**
 *
 * $Id$
 */
package gemRBAC.validation;

import gemRBAC.Delegation;
import gemRBAC.History;
import gemRBAC.Role;
import gemRBAC.Session;
import gemRBAC.SpatialContext;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link gemRBAC.User}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UserValidator {
	boolean validate();

	boolean validateIdUser(String value);
	boolean validateRoles(EList<Role> value);
	boolean validateSessions(EList<Session> value);
	boolean validateDelegation(EList<Delegation> value);
	boolean validateRecieveddelegation(EList<Delegation> value);
	boolean validateRevocation(EList<Delegation> value);
	boolean validateDelegatedRoles(EList<Role> value);
	boolean validateUserLocation(SpatialContext value);
	boolean validateUserLog(EList<History> value);
}
